name: Fast-forward check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Check if fast-forwarding is possible
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: false
          # Only comment on the PR when fast-forwarding is NOT possible
          comment: on-error
